src/app.ts, src/app_test.tsx, src/exec_context.ts, src/util.ts
Allows multiple updaters to be sequenced together like so:
```javascript
container({
// ...
update: [
[ToggleThingAndGoHome, seq(
evolve({ thing: not }),
commands(Browser.PushHistory, { path: '/home' })
)]
});
```
Also: misc. copy changes, slight test rearranging.
=> Implement helper for sequencing multiple updaters

src/app.ts, src/app_test.tsx
Implements new updater helper functions, modifies `commands()` to accept empty (no-op) constructors.
=> New helpers

src/view_wrapper.tsx
Taking advantage of `Pure Components` as opposed to `Components`
=> Pure Components

.gitignore, src/app.ts, src/message.ts, src/view_wrapper.tsx, src/view_wrapper_test.tsx
`Refresh` allows the container to preform an update on `componentWillReceiveProps `
`Deactivate` allows the container to preform an update on `componentWillUnmount`
I feel like my test for `Deactivate` is a little hacky, but AFAIK there is no good wait to `isolate` the container, but still use enzyme to render the view. So I did the next best thing.
Also updated the `.gitignore` for `.vscode`
=> Refresh and Deactivate

src/app.ts, src/exec_context.ts, src/view_wrapper.tsx, src/view_wrapper_test.tsx
- Decoupled `Environment` from `Container` so by default when you export `container` is has no environment.
- If a `Container` has no parent, and no `Environment` it defaults the `stateManager` in `exec_context`
- Made `defaultEnv` an export so the user can use it if needed.
- Wrote a test where `ContainerA` has an environment with `TestCommand` and `ContainerB` dispatches `TestCommand` that triggers a result `Message` to change state
If you think of any additional test cases please let me know.
=> Cascade Effect Handlers

src/environment.ts, src/view_wrapper.tsx
It seems as though  in`mergeEnv` `parent instanceof ExecContext` was showing true if it was 
of type `ExecContextPartial`. Also needed to make `delegate.toString()` to be able to print symbol. Whoops!
@nateabele any reason as to why `parent instanceof ExecContext` was triggering true for isolate?
=> Isolate bug in mergeEnv fixed

package.json, src/view_wrapper.tsx, src/view_wrapper_test.tsx
So `Refresh` does not break with React 16.
=> Refresh Moved to componentDidUpdate

package.json, src/view_wrapper.tsx
With React 16 children now have a property of `_owner` that has a bunch of unique data that was failing when comparing old and new props. Causing in our app weird side effects. We talked about this slightly via slack yesterday @nateabele. OH and I had to bump version by 2 since I was dumb and did not do the last publish from `/dist` . 😢
=> Omitting children from Activate, Deactivate, Refresh

src/util.ts
Outputs all parameters passed to `log()` — still only returns the first one.
=> Log extra values passed to `log()`

src/dev_tools.ts
Exposes `context.id` on a Message as `context` in the serialized data that is sent to the devtools extension. This allows for an upcoming feature in devtools that requires the context to be known.
=> Expose Context ID on Messages sent to DevTools

package.json
Axiom is using axios 17 (causing a casium peer dependency warning), and I doubt there is a reason that we need exactly axios 0.16 here, so I figured I'd add this guy too.
=> Support axios 17

.circleci/config.yml, .gitignore, package.json, yarn.lock
- Wraps the `test` script in `nyc` with a TypeScript-compatible configuration
- Publishes coverage report to CodeClimate during CI
I've configured CodeClimate and CircleCI on my fork to prove that this works. To configure for the mainline repo, you'll need to get the CodeClimate Test Report ID from their configuration page, and add it as an environment variable on CircleCI named `CC_TEST_REPORTER_ID`.
=> Add test coverage collection

src/core_test.tsx, src/runtime/exec_context.ts
@nateabele As far as I can tell, the change to subscription behaviour (as seen in the change to the unit test) is correct, but let me know if notification to subscribers should be skipped on init.
=> Call run() on containers without an `init` function

src/core.ts, src/core_test.tsx, src/runtime/exec_context.ts, src/util.ts
Allows the recursive behaviour allowed by 'seq' to be used by 'mapMessage'. This encourages updaters such as:
```
[Msg, (model, msg) => evolve({count: inc(msg.step)}, model)]
```
To be refactored to:
```
[Msg, (model, msg) => evolve({count: inc(msg.step)})]
```
=> Extract reducer used by 'seq' to 'reduceUpdater' util function

src/commands/browser.ts, src/commands/cookies.ts, src/commands/cookies_test.ts, src/commands/http.ts, src/commands/http_test.ts, src/commands/local_storage.ts, src/runtime/exec_context.ts, src/util.ts
Adds a `moduleName` decorator the the `util` module, which allows the `name` property of a class' Constructor to be prepended with a string.
This allows the built-in Effect classes a way to expose the module they belong to, and greatly simplifies the implementation of `cmdName` and removes the need to enumerate the built-in Effect classes.
---
This PR targets the `next` branch due to BC break
=> Use Decorators to explicitly prefix Command Constructor names

src/core.ts
By marking parameters as optional, TypeScript requires verbose guards when running in strict mode. I do not think these parameters should be marked as optional, as Casium will always supply them internally. However, it is up to the implementer to actually use them.
By marking them as non-optional, type checking and completion when writing updater and view functions is a much more pleasant experience.
In order to achieve this, the `UpdaterDef` and `ContainerViewDef` type aliases have been introduced, which mirror their existing counterparts but do not contain optional parameters. These types are presented to consumerrs of `container` when writing Updater and View functions.
This PR also adds support for function-returning Updaters to `UpdateResult` - since an Updater can now return a …
=> Remove optional parameters on updater and view functions

src/view_wrapper.tsx
Uses `equals` to prevent superfluous renders of components when props and state are equivalent by value.
=> Perform prop & state comparison in `ViewWrapper`

src/runtime/exec_context.ts, src/util.ts, src/view_wrapper.tsx
This PR addresses the points raised in #55, with the exception of the fifth point (DevTools integration).
- The old behaviour of `trap` has been restored, which spreads the rest'ed input parameters to the error handler function, meaning that those useless error messages about arrays have now gone away.
- Due to the awkward arrangement of parameters given to the error logging function, I've separated them into two different functions. In this case, I'm willing to sacrifice some repetition in order to make the execution path easier to understand.
- I've hoisted the functions that extract message/command constructor names out to the `util` module. They seem to be more at home there.
- The ViewWrapper error handling has been extracted to another method so that we can support both …
=> Improved Error Handling & Reporting

package-lock.json, package.json, src/containers/input.tsx, src/util.ts, src/util_test.ts
Adds type definitions for `withProps` so we can get rid of all the monkey-patching downstream.
=> Properly type withProps

package.json
Previously, the README wasn't included in the distro which, due to an earlier NPM bug, was causing the package page to render empty.
This makes sure it's always included.
=> Make sure README gets into the distro

package.json, src/containers/input.tsx, src/core.ts, src/core_test.tsx, src/dispatcher_test.ts, src/effects/index.ts, src/effects/local_storage.ts, src/environment.ts, src/message.ts, src/runtime/exec_context.ts, src/util.ts, src/view_wrapper.tsx, yarn.lock
In addition to being quite slow, Ramda's `equals` implementation can't handle symbol keys. This PR pulls in a forked version of `fast-deep-equals` which _can_ handle symbol keys. Incidentally it's also pretty fast:
```
fast-deep-equal x 208,559 ops/sec ±1.57% (86 runs sampled)
fast-deep-equal/es6 x 82,924 ops/sec ±0.52% (87 runs sampled)
fast-equals x 192,611 ops/sec ±3.52% (85 runs sampled)
nano-equal x 160,518 ops/sec ±0.65% (91 runs sampled)
shallow-equal-fuzzy x 141,525 ops/sec ±0.50% (89 runs sampled)
underscore.isEqual x 95,010 ops/sec ±0.61% (90 runs sampled)
lodash.isEqual x 32,457 ops/sec ±0.57% (89 runs sampled)
deep-equal x 175 ops/sec ±1.87% (52 runs sampled)
deep-eql x 33,933 ops/sec ±0.57% (92 runs sampled)
ramda.equals x 10,357 ops/sec ±0.49% (85 runs sampled) …
```
=> Upgrade equals comparisons

package.json, src/commands/http.ts, src/effects/http.ts
Allows setting Axios' `responseType` field in the request config
[Request Config](https://github.com/axios/axios/blob/master/README.md#request-config):
> `responseType` indicates the type of data that the server will respond with options are: 'arraybuffer', 'document', 'json', 'text', 'stream'
> browser only: 'blob'
=> Allow setting axios responseType via HTTP Request
